name: File Change Trigger

on:
  push:
    paths:
      - 'testdir/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Project
        run: echo "Building project..."

